# Generated by Django 4.1.5 on 2023-02-04 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "information",
                    models.BooleanField(help_text="Is this information only?"),
                ),
                ("text", models.TextField()),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("T", "Twitter"),
                            ("M", "Mastodon"),
                            ("1", "TfL API StopPoint Disruption (v1)"),
                            ("2", "TfL API Disruptions Lifts (v2)"),
                            ("K", "TfL Trackernet"),
                            ("U", "User"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stations.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "information",
                    models.BooleanField(help_text="Is this information only?"),
                ),
                ("text", models.TextField()),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                ("reports", models.ManyToManyField(to="incidents.report")),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stations.station",
                    ),
                ),
            ],
        ),
    ]
