# Generated by Django 4.1.5 on 2023-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "naptan_id",
                    models.CharField(max_length=32, verbose_name="NaPTAN ID"),
                ),
                ("notes", models.TextField()),
                (
                    "step_to_train",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("G", "0 - 50mm (0 - 2 inches)"),
                            ("A", "51 - 120mm (2 - 4.7 inches)"),
                            ("R", "Over 120mm (4.7 inches)"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "gap_to_train",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "0 - 85mm (0 - 3.3 inches)"),
                            ("B", "86 - 180mm (3.3 - 7 inches)"),
                            ("C", "Over 180mm (7 inches)"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "designated_boarding_point",
                    models.BooleanField(blank=True, null=True),
                ),
                ("access_via_ramp", models.BooleanField(blank=True, null=True)),
                ("access_via_lift", models.BooleanField(blank=True, null=True)),
                (
                    "connection_to_nr",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Connection to National Rail",
                    ),
                ),
                ("tube", models.BooleanField()),
                ("dlr", models.BooleanField(verbose_name="DLR")),
                ("national_rail", models.BooleanField(verbose_name="National Rail")),
                ("crossrail", models.BooleanField()),
                ("overground", models.BooleanField()),
            ],
        ),
    ]
