# Generated by Django 4.1.6 on 2023-02-04 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0003_alter_station_naptan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="alternate_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), null=True, size=None
            ),
        ),
    ]
