# Generated by Django 4.1.7 on 2023-02-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0005_station_hub_naptan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="parent_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stations.station",
            ),
        ),
    ]
