# Generated by Django 4.1.6 on 2023-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="crossrail",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="dlr",
            field=models.BooleanField(blank=True, null=True, verbose_name="DLR"),
        ),
        migrations.AlterField(
            model_name="station",
            name="national_rail",
            field=models.BooleanField(null=True, verbose_name="National Rail"),
        ),
        migrations.AlterField(
            model_name="station",
            name="overground",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="tube",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
